---
namespace: netcloud
name: ncae
version: 1.0.1
authors:
  - Andreas Graber <graber@netcloud.ch>
  - Pascal Mathis <mathis@netcloud.ch>
  - Richard Strnad <strnad@netcloud.ch>
description: Ansible collection for interacting with Netcloud Automation Engine (NCAE)
readme: README.md
license_file: COPYING
tags:
  - infrastructure
  - ncae
  - netcloud
  - automation
  - engine
dependencies: {}
repository: https://github.com/netcloud/ncae-ansible-collection
homepage: https://www.netcloud.ch
issues: https://github.com/netcloud/ncae-ansible-collection/issues
build_ignore: []
