---
- name: Detect if module execution is simulated
  ansible.builtin.set_fact:
    ncae_module_simulation: >-
      {{
        (tower_job_id is not defined) and
        (service_id is not defined) and
        (service_instance_id is not defined)
      }}
  when: ncae_module_simulation is not defined

- name: Prepare environment for simulation
  when: ncae_module_simulation
  block:
    - name: Set well-known variables from NCAE Core
      ansible.builtin.set_fact:
        callback_url: null
        logger_url: null
        service_id: 0
        service_instance_id: 0

- name: Log playbook execution to NCAE
  ansible.builtin.include_tasks:
    file: log.yml
  vars:
    log_title: '*** Playbook Execution Started **'
    log_text: >-
      Started processing tasks for NCAE service instance
      {{ ("#" ~ service_instance_id) if service_instance_id else "<unknown>" }}
      for service
      {{ ("#" ~ service_id) if service_id else "<unknown>" }}
      with {{ devices | default([]) | length }} devices.

- name: Transform payload credentials into Ansible credentials
  ansible.builtin.set_fact:
    ansible_user: >-
      {{
        (devices | selectattr('id', 'eq', ncae_device_id) | first | default({}))
        .credential.username | default(ansible_user | default(omit))
      }}
    ansible_password: &password >-
      {{
        (devices | selectattr('id', 'eq', ncae_device_id) | first | default({}))
        .credential.password | default(ansible_password | default(omit))
      }}
    ansible_become_password: *password
