---
- name: 'Update the NCAE CMDB'
  ansible.builtin.uri:
    url: '{{ cmdb_url }}'
    method: PATCH
    headers:
      Cookie: '{{ AUTH_COOKIE }}'
    validate_certs: false
    body_format: json
    body:
      callback_data: '{{ CMDB_DATA }}'
  delegate_to: localhost
...
